version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db
    networks:
      - stockecom-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - stockecom-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    env_file:
      - ./frontend/.env
    depends_on:
      - django
    networks:
      - stockecom-network

# Define volumes for persistent storage
volumes:
  postgres_data:

# Define a shared network for all services
networks:
  stockecom-network:
    driver: bridge
